### ISSUE TITLE
doc link auto-parameter-tupling.html doesn't work

### ISSUE THREAD

**Issue by tumakha** [scala/scala3-example-project#37]
https://github.com/lampepfl/dotty-example-project/blob/2c1e96f4a4a0a7128e4a12690ccfba794b714fe8/src/main/scala/AutoParamTupling.scala#L3

**Comment by tumakha** [comment]
The correct link is https://dotty.epfl.ch/docs/reference/other-new-features/parameter-untupling.html

**Comment by SethTisue** [comment]
a PR on this would be very welcome

**Comment by liufengyun** [comment]
Fixed in #55.
