### ISSUE TITLE
Move `mill` branch to `dotty-staging/scala3-example-project`

### ISSUE THREAD

**Issue by nicolasstucki** [scala/scala3-example-project#62]

**Comment by anatoliykmetyuk** [comment]
Why do you think it should be moved? This branch is not really a work in progress but a user-facing demo. Maybe a better idea would be to create a separate example project for mill.

**Comment by nicolasstucki** [comment]
Having a `scala3-mill-example-project` would be much clearer for users. The other thing that might be useful is to have a `scala3-mill.g8` template.

This also begs the question if we should rename this project to `scala3-sbt-example-project`.

**Comment by hmf** [comment]
Just my 2 cents: if I understood correctly,I think moving Mill to a separate project will increase the maintenance burden. Updates will have to be repeated, no? As a Mill user, if I see a build.sc and the README.md that says this project has SBT and Mill example projects, then its good enough.

**Comment by nicolasstucki** [comment]
The two branches already contain two distinct projects. Putting it in another project would not decrease maintainability by much. We already have to maintain all the `scaal3-xyz.g8` projects at the same time which has not been hard.

Having two projects will benefit users as it will be simpler to find and navigate the examples for each build tool.

**Comment by nicolasstucki** [comment]
BTW. By having it in another branch we did not notice that there is no badge in the mill example project readme and that the build is failling.

**Comment by nicolasstucki** [comment]
Moved to https://github.com/dotty-staging/scala3-example-project/tree/mill
