### ISSUE TITLE
scala 3 vs scala 2

### ISSUE THREAD

**Issue by xhudik** [scala/scala3-example-project#65]
Hi, a newbie question: 
if I add `println(Console.YELLOW + s"Scala version = ${util.Properties.versionString}")` into `Main.scala` and run `sbt run` I got:
```
Scala version = 2.13.4
Trait Params example:
Hello Dotty!

...
```
Any idea why I'm getting 2.13.4 instead of Scala 3.0.0RC1? (the true is that I have installed Scala 2.13.4 on my local laptop)

**Comment by bishabosha** [comment]
Yes, this is because Scala 3.0.0-RC1 reuses the standard library from 2.13.4, where `scala.util.Properties` is defined. The version number comes from a file shipped in the `org.scala-lang:scala-library:2.13.4` JAR.

**Comment by xhudik** [comment]
Thanks @bishabosha ; 
will final Scala 3 uses its own standard library? Other question - is there any way to find out what scala version is running the app?

**Comment by bishabosha** [comment]
> is there any way to find out what scala version is running the app?

if your application includes the `scala3-compiler_3.0.0-RC1` library in the classpath then you can use `dotty.tools.dotc.config.Properties.versionString` to get the same thing, or `dotty.tools.dotc.config.Properties.versionMsg` to include copyright message and optional git hash if it is a nightly

**Comment by xhudik** [comment]
indeed, this is working - thank you @bishabosha !! I'm closing the issue
